# Generated by Django 2.2.7 on 2019-11-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='long_lat',
            new_name='geolocation',
        ),
    ]
